### ISSUE TITLE
scip-go doesn’t consider replace directives

### ISSUE THREAD

**Issue by efritz** [sourcegraph/scip-go#13]
The symbol names I’m getting are `scip-go import "scip-go gomod [github.com/go-nacelle/config/v2](http://github.com/go-nacelle/config/v2) v2.0.1 [github.com/go-nacelle/config/v2/NewEnvSourcer()](http://github.com/go-nacelle/config/v2/NewEnvSourcer())."`, but I would expect it to be `sourcegraph-testing/nacelle-config/v5 v5.0.0` instead based on the go.mod contents

See https://github.com/sourcegraph-testing/nacelle/commit/68d3125fb03d4aec540714577401f9f01adffa8a.

**Comment by efritz** [comment]
Have: `scip-go gomod github.com/go-nacelle/config/v2 v2.0.1 http://github.com/go-nacelle/config/v2/NewEnvSourcer().`
Want: `scip-go gomod github.com/sourcegraph-testing/nacelle-config/v5 v5.0.0 http://github.com/go-nacelle/config/v2/NewEnvSourcer().`

**Comment by tjdevries** [comment]
I fixed this -- the main problem was actually module resolution. Fixed with #17
