### ISSUE TITLE
Panic when using the new slices stdlib package in go 1.21

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/scip-go#48]
Minimal repo: https://github.com/varungandhi-src/slice_test

On attempting to index it with scip-go 0.1.5 (the latest release) or with `main`, we get a crash.

```
panic: Should not be possible to have nil module for userland package: slices slices

goroutine 5 [running]:
github.com/sourcegraph/scip-go/internal/loader.normalizePackage(0x1400004a550, 0x140004b3e00)
        /Users/varun/Code/scip-go/internal/loader/loader.go:148 +0x6b4
github.com/sourcegraph/scip-go/internal/loader.addImportsToPkgs(0x140004e1e28?, 0x14000104a80?, 0x140004b3e00)
        /Users/varun/Code/scip-go/internal/loader/loader.go:49 +0x58
github.com/sourcegraph/scip-go/internal/loader.addImportsToPkgs(0x140000e4728?, 0x14000310050?, 0x140004b4480)
        /Users/varun/Code/scip-go/internal/loader/loader.go:53 +0xf4
github.com/sourcegraph/scip-go/internal/loader.LoadPackages.func1()
        /Users/varun/Code/scip-go/internal/loader/loader.go:86 +0x168
github.com/sourcegraph/scip-go/internal/parallel.Run.func1()
        /Users/varun/Code/scip-go/internal/parallel/parallel.go:25 +0x88
created by github.com/sourcegraph/scip-go/internal/parallel.Run
        /Users/varun/Code/scip-go/internal/parallel/parallel.go:21 +0x5c
```

**Comment by fkling** [comment]
Please forgive me for intruding here, but is more work needed to prevent this from happening again? It seems bad to me that this can happen by just upgrading Go. I guess if we don't know that something is a standard module then we can't index it correctly. Don't know what the alternative would be, but I guess anything is better than a panic?

**Comment by varungandhi-src** [comment]
You're totally right. I discussed this issue with TJ in Slack earlier (https://sourcegraph.slack.com/archives/C03C5EFRMR8/p1691723965644199) because I agree, this isn't a good experience. I've filed a GitHub issue: https://github.com/sourcegraph/scip-go/issues/51, and am looking to fix it soon.
